---
- name: Install Glance
  apt:
    name:
      - glance
    state: latest

- name: Configure database access
  replace:
    dest: /etc/glance/glance-api.conf
    regexp: connection = mysql+pymysql://glance:GLANCE_DBPASS@controller/glance
    replace: connection = mysql+pymysql://glance:admin123@controller/glance
    backup: yes

- name: Configure Glance Authentication Key for database
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[keystone_authtoken\]'
    line: "{{ item }}"
    state: present
    backup: yes

  loop:
    - www_authenticate_uri = http://controller:5000
    - auth_url = http://controller:5000
    - memcached_servers = controller:11211
    - auth_type = password
    - project_domain_name = Default
    - user_domain_name = Default
    - project_name = service
    - username = glance
    - password = admin123

- name: Configure Glance paste_deploy
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[paste_deploy\]'
    line: 'flavor = keystone'
    backup: yes

- name: Configure Glance glance_store
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[glance_store\]'
    line: "{{ item }}"
    state: present
    backup: yes

  loop:
    - stores = file,http
    - default_store = file
    - filesystem_store_datadir = /var/lib/glance/images/

- name: Configure Glance oslo_limit
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[oslo_limit\]'
    line: "{{ item }}"
    state: present
    backup: yes

  loop:
    - auth_url = http://controller:5000
    - auth_type = password
    - user_domain_id = default
    - username = MY_SERVICE
    - system_scope = all
    - password = MY_PASSWORD
    - endpoint_id = ENDPOINT_ID
    - region_name = RegionOne

- name: Configure the default of Glance
  lineinfile:
    dest: /etc/glance/glance-api.conf
    insertafter: '\[DEFAULT\]'
    line: 'use_keystone_limits = True'
    backup: yes

- name: Populating the Image Service Database
  become: yes
  shell:
    sudo glance-manage db_sync
