- name: Installing the Keystone
  apt:
    name: keystone
    state: latest

- name: Configuring the Config File
  lineinfile:
    dest: /etc/keystone/keystone.conf
    insertafter: '\[database\]'
    regexp: 'connection = mysql+pymysql://keystone:KEYSTONE_DBPASS@controller/keystone'
    line: 'connection = mysql+pymysql://keystone:admin123@controller/keystone'
    backup: yes
    backrefs: yes

- name: Configure Config File
  lineinfile:
    dest: /etc/keystone/keystone.conf
    insertafter: '\[token\]'
    line: 'provider = fernet'
    backup: yes

- name: Populating the Database
  become: yes
  shell:
    keystone-manage db_sync

- name: Initialize the Fernet Key
  shell:
    keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: Initialize the Fernet Key
  shell:
     keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- name: Configuring the Apache Server
  lineinfile:
    dest: /etc/apache2/apache2.conf
    line: 'ServerName controller'
    state: present
    backup: yes

- name: Configure Administrative Account
  shell:
    export OS_USERNAME=admin
    export OS_PASSWORD=ADMIN_PASS
    export OS_PROJECT_NAME=karlo
    export OS_USER_DOMANI_NAME=Default
    export OS_PROJECT_DOMAIN_NAME=Default
    export OS_AUTH_URL=http://controller:5000/v3
    export OS_IDENTITY_API_VERSION=3

- block:
  - name: Verify if already running
    shell: keystone-manage --help
    register: keystone_service
